packages:
  - "apps/*"
  - "packages/*"
  - "db"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  msgpackr-extract: true
  prisma: true
minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1125.0'
  - '@aws-sdk/s3-request-presigner@3.1125.0'
